-- 1. Projects Table: Stores repo details
CREATE TABLE public.projects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    remote_url TEXT UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Heartbeats Table: Stores activity pulses
CREATE TABLE public.heartbeats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL, -- You can use a fixed UUID or your Supabase Auth user ID
    project_id UUID REFERENCES public.projects(id),
    language TEXT,
    file_path TEXT,
    branch TEXT,
    editor TEXT,
    os TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Daily Stats Table: For quick dashboard summaries
CREATE TABLE public.daily_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    date DATE DEFAULT CURRENT_DATE NOT NULL,
    total_seconds INTEGER DEFAULT 0 NOT NULL,
    primary_language TEXT,
    UNIQUE(user_id, date)
);
